let length = 16;
let weight = 7.5;
let color = "Yellow";
let lastName = "Johnson";
let x = true;
let y = false;
const person = {firstName:"John", lastName:"Doe"};
const cars = ["Saab", "Volvo", "BMW"];
const date = new Date("2022-03-25");
console.log("length:", length);
console.log("weight:", weight);
console.log("color:", color);
console.log("lastName:", lastName);
console.log("x:", x);
console.log("y:", y);
console.log("person:", person);
console.log("cars:", cars);
console.log("date:", date);